[package]
name = "voxelizer"
version = "0.1.0"
edition = "2021"

[dependencies]
gltf = "1.4.1"
nalgebra = "0.33.2"
ahash = "0.8.11"
bvh = { version = "0.10.0" }
obj-rs = "0.7.4"
image = "0.25.5"
rayon = "1.10.0"
clap = { version = "4.5.28", features = ["derive"] }
indicatif = "0.17.11"
